// src/App.tsx
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { getCurrentUser, logout, formatCurrency } from './lib/api';
import { User, Wallet, WalletTransaction } from './types';
import AuthScreen from './components/AuthScreen';
import Dashboard from './components/Dashboard';
import WalletsView from './components/WalletsView';
import TransactionsView from './components/TransactionsView';
import BudgetsView from './components/BudgetsView';
import GoalsView from './components/GoalsView';
import { 
  LayoutDashboard, Wallet as WalletIcon, ArrowDownUp, 
  PieChart, Target, LogOut, User as UserIcon, Menu, X, Wallet2, Sparkles
} from 'lucide-react';

export default function App() {
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [activeTab, setActiveTab] = useState<string>('dashboard');
  const [selectedWallet, setSelectedWallet] = useState<Wallet | null>(null);
  const [selectedTx, setSelectedTx] = useState<WalletTransaction | null>(null);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  // Initialize auth
  useEffect(() => {
    const user = getCurrentUser();
    if (user) {
      setCurrentUser(user);
    }
  }, []);

  const handleAuthSuccess = () => {
    const user = getCurrentUser();
    if (user) {
      setCurrentUser(user);
      setActiveTab('dashboard');
    }
  };

  const handleLogout = () => {
    logout();
    setCurrentUser(null);
  };

  if (!currentUser) {
    return <AuthScreen onAuthSuccess={handleAuthSuccess} />;
  }

  // Navigation Items
  const navItems = [
    { id: 'dashboard', label: 'Tableau de Bord', icon: LayoutDashboard },
    { id: 'wallets', label: 'Mes Comptes', icon: WalletIcon },
    { id: 'transactions', label: 'Transactions', icon: ArrowDownUp },
    { id: 'budgets', label: 'Budgets', icon: PieChart },
    { id: 'goals', label: 'Cagnottes', icon: Target },
  ];

  const handleTabChange = (tabId: string) => {
    setActiveTab(tabId);
    setMobileMenuOpen(false);
  };

  return (
    <div className="min-h-screen bg-slate-50/70 text-slate-800 flex flex-col md:flex-row font-sans selection:bg-emerald-500/20">
      
      {/* Mobile Top Header */}
      <header className="md:hidden bg-white border-b border-slate-100 px-4 py-3 flex items-center justify-between sticky top-0 z-40">
        <div className="flex items-center gap-2">
          <div className="h-9 w-9 bg-emerald-600 rounded-xl flex items-center justify-center text-white shadow-sm">
            <Wallet2 className="h-5 w-5" />
          </div>
          <span className="font-bold text-lg text-slate-900 tracking-tight flex items-center gap-1.5">
            harena
            <span className="text-[10px] bg-emerald-500/10 text-emerald-600 font-bold px-2 py-0.5 rounded-full uppercase">
              MGA
            </span>
          </span>
        </div>
        <button 
          onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
          className="text-slate-500 p-1.5 hover:bg-slate-100 rounded-xl cursor-pointer"
        >
          {mobileMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
        </button>
      </header>

      {/* Sidebar Navigation */}
      <aside className={`
        fixed inset-y-0 left-0 w-64 bg-white border-r border-slate-100 flex flex-col justify-between z-30 transition-transform duration-300 md:translate-x-0 md:static md:h-screen shrink-0
        ${mobileMenuOpen ? 'translate-x-0 pt-16 md:pt-0' : '-translate-x-full md:translate-x-0'}
      `}>
        <div className="px-5 py-6 space-y-6">
          {/* Logo Brand */}
          <div className="hidden md:flex items-center gap-2.5">
            <div className="h-10 w-10 bg-emerald-600 rounded-2xl flex items-center justify-center text-white shadow-md">
              <Wallet2 className="h-6 w-6" />
            </div>
            <div className="flex flex-col">
              <span className="font-extrabold text-xl text-slate-900 tracking-tight flex items-center gap-1.5 leading-none">
                harena
                <span className="text-[9px] bg-emerald-100 text-emerald-800 font-bold px-1.5 py-0.5 rounded-md uppercase">
                  MGA
                </span>
              </span>
              <span className="text-[10px] text-slate-400 mt-1 font-medium">Portefeuille Intelligent</span>
            </div>
          </div>

          {/* Navigation Links */}
          <nav className="space-y-1.5 pt-4">
            {navItems.map((item) => {
              const Icon = item.icon;
              const isActive = activeTab === item.id;
              return (
                <button
                  key={item.id}
                  onClick={() => handleTabChange(item.id)}
                  className={`w-full flex items-center gap-3 px-4 py-3 rounded-2xl text-sm font-semibold transition-all cursor-pointer ${
                    isActive 
                      ? 'bg-slate-900 text-white shadow-sm shadow-slate-900/10' 
                      : 'text-slate-500 hover:text-slate-800 hover:bg-slate-50'
                  }`}
                >
                  <Icon className={`h-5 w-5 ${isActive ? 'text-emerald-400' : 'text-slate-400 group-hover:text-slate-600'}`} />
                  <span>{item.label}</span>
                </button>
              );
            })}
          </nav>
        </div>

        {/* User Profile Widget */}
        <div className="p-5 border-t border-slate-100 bg-slate-50/50">
          <div className="flex items-center gap-3 mb-4">
            <div className="h-10 w-10 rounded-2xl bg-emerald-100 flex items-center justify-center text-emerald-700 border border-emerald-200">
              <UserIcon className="h-5 w-5" />
            </div>
            <div className="flex-1 min-w-0">
              <h4 className="font-bold text-slate-800 text-sm truncate leading-none">
                {currentUser.firstname} {currentUser.lastname}
              </h4>
              <span className="text-xs text-slate-400 truncate block mt-1 font-mono">
                @{currentUser.username}
              </span>
            </div>
          </div>
          <button
            onClick={handleLogout}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-2xl text-xs font-bold text-rose-600 hover:text-white border border-rose-100 hover:bg-rose-500 hover:border-rose-500 transition-all cursor-pointer"
          >
            <LogOut className="h-4 w-4" />
            <span>Se déconnecter</span>
          </button>
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="flex-1 md:h-screen md:overflow-y-auto px-4 py-6 md:p-8 space-y-6">
        {activeTab === 'dashboard' && (
          <Dashboard 
            currentUser={currentUser} 
            setActiveTab={setActiveTab}
            setSelectedWallet={setSelectedWallet}
            setSelectedTx={setSelectedTx}
          />
        )}
        {activeTab === 'wallets' && (
          <WalletsView 
            currentUser={currentUser}
            selectedWallet={selectedWallet}
            setSelectedWallet={setSelectedWallet}
          />
        )}
        {activeTab === 'transactions' && (
          <TransactionsView 
            currentUser={currentUser}
            selectedTx={selectedTx}
            setSelectedTx={setSelectedTx}
          />
        )}
        {activeTab === 'budgets' && (
          <BudgetsView currentUser={currentUser} />
        )}
        {activeTab === 'goals' && (
          <GoalsView currentUser={currentUser} />
        )}
      </main>

    </div>
  );
}

// src/app/app.component.ts
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Component, OnInit } from "@angular/core";
import { CommonModule } from "@angular/common";
import { AuthComponent } from "./components/auth/auth.component";
import { DashboardComponent } from "./components/dashboard/dashboard.component";
import { AnalyticsComponent } from "./components/analytics/analytics.component";
import { AiInsightsComponent } from "./components/ai-insights/ai-insights.component";
import { User, Wallet, WalletTransaction } from "../types";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [
    CommonModule,
    AuthComponent,
    DashboardComponent,
    AnalyticsComponent,
    AiInsightsComponent
  ],
  template: `
    <main class="min-h-screen bg-slate-50 text-slate-800">
      <!-- Unauthenticated View -->
      <app-auth *ngIf="!token" (loginSuccess)="handleLoginSuccess($event)"></app-auth>

      <!-- Authenticated Layout -->
      <div *ngIf="token" class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <!-- Modern App Navigation Header -->
        <header class="flex flex-col sm:flex-row sm:items-center sm:justify-between pb-6 mb-8 border-b border-slate-200 gap-4">
          <div class="flex items-center gap-3">
            <div class="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center shadow-md shadow-indigo-600/10">
              <svg class="w-5 h-5 text-white stroke-[2.5]" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                <rect x="3" y="5" width="18" height="14" rx="2" />
                <path d="M3 10h18" />
              </svg>
            </div>
            <div>
              <h1 class="text-xl font-bold tracking-tight text-slate-900 flex items-center gap-2">
                Harena
                <span class="text-[10px] bg-indigo-50 border border-indigo-100 text-indigo-600 font-mono font-bold uppercase px-1.5 py-0.5 rounded">
                  {{ currentUser?.username || "PORTFOLIO" }}
                </span>
              </h1>
              <p class="text-[11px] text-slate-400 font-semibold uppercase font-mono mt-0.5">
                Le Portefeuille Intelligent
              </p>
            </div>
          </div>

          <!-- Tab Selector Buttons -->
          <div class="flex items-center gap-2 bg-slate-100 p-1.5 rounded-xl border border-slate-200 shrink-0 self-start sm:self-auto">
            <button
              (click)="setActiveTab('dashboard')"
              class="px-4 py-2 text-xs font-bold rounded-lg transition-all flex items-center gap-1.5 cursor-pointer"
              [ngClass]="{
                'bg-white text-slate-900 shadow-sm': activeTab === 'dashboard',
                'text-slate-500 hover:text-slate-900': activeTab !== 'dashboard'
              }"
            >
              <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <rect x="3" y="3" width="7" height="9" />
                <rect x="14" y="3" width="7" height="5" />
                <rect x="14" y="12" width="7" height="9" />
                <rect x="3" y="16" width="7" height="5" />
              </svg>
              <span>Accueil</span>
            </button>

            <button
              (click)="setActiveTab('analytics')"
              class="px-4 py-2 text-xs font-bold rounded-lg transition-all flex items-center gap-1.5 cursor-pointer"
              [ngClass]="{
                'bg-white text-slate-900 shadow-sm': activeTab === 'analytics',
                'text-slate-500 hover:text-slate-900': activeTab !== 'analytics'
              }"
            >
              <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <line x1="18" y1="20" x2="18" y2="10" />
                <line x1="12" y1="20" x2="12" y2="4" />
                <line x1="6" y1="20" x2="6" y2="14" />
              </svg>
              <span>Analyses</span>
            </button>

            <button
              (click)="setActiveTab('ai')"
              class="px-4 py-2 text-xs font-bold rounded-lg transition-all flex items-center gap-1.5 cursor-pointer"
              [ngClass]="{
                'bg-white text-slate-900 shadow-sm': activeTab === 'ai',
                'text-slate-500 hover:text-slate-900': activeTab !== 'ai'
              }"
            >
              <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
              </svg>
              <span>Conseils IA</span>
            </button>
          </div>

          <!-- User Quick-Bar & Logout -->
          <div class="flex items-center gap-3">
            <div class="bg-indigo-50 border border-indigo-100 text-indigo-700 font-bold text-xs px-3.5 py-2 rounded-xl flex items-center gap-1.5">
              <svg class="w-4 h-4 stroke-[2.5]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
                <circle cx="12" cy="7" r="4" />
              </svg>
              <span>{{ currentUser?.firstname || "Utilisateur" }}</span>
            </div>

            <button
              (click)="handleSignOut()"
              class="p-2.5 text-slate-500 hover:text-rose-600 bg-slate-100 hover:bg-rose-50 rounded-xl border border-slate-200 hover:border-rose-100 transition-all cursor-pointer"
              title="Se déconnecter"
            >
              <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5">
                <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
                <polyline points="16 17 21 12 16 7" />
                <line x1="21" y1="12" x2="9" y2="12" />
              </svg>
            </button>
          </div>
        </header>

        <!-- Dynamic View Sections -->
        <div>
          <!-- Tab 1: Dashboard component -->
          <app-dashboard
            *ngIf="activeTab === 'dashboard'"
            [token]="token"
            [userId]="userId"
            [selectedWallet]="selectedWallet"
            [wallets]="wallets"
            [refreshTrigger]="refreshTrigger"
            (walletSelected)="handleWalletSelect($event)"
            (analyzeTx)="handleAnalyzeTransaction($event)"
            (triggerRefresh)="triggerRefresh()"
          ></app-dashboard>

          <!-- Tab 2: Analytics component -->
          <app-analytics
            *ngIf="activeTab === 'analytics'"
            [selectedWallet]="selectedWallet"
            [transactions]="allTransactions"
          ></app-analytics>

          <!-- Tab 3: AI Recommendations -->
          <app-ai-insights
            *ngIf="activeTab === 'ai' || analyzingTransaction"
            [token]="token"
            [selectedWallet]="selectedWallet"
            [analyzingTransaction]="analyzingTransaction"
            (closeAnalysisModal)="handleCloseAnalysis()"
          ></app-ai-insights>
        </div>
      </div>
    </main>
  `,
  styles: []
})
export class AppComponent implements OnInit {
  token = localStorage.getItem("harena_token") || "";
  userId = localStorage.getItem("harena_uid") || "";
  currentUser: User | null = null;

  wallets: Wallet[] = [];
  selectedWallet: Wallet | null = null;
  analyzingTransaction: WalletTransaction | null = null;

  activeTab: "dashboard" | "analytics" | "ai" = "dashboard";
  refreshTrigger = 0;
  allTransactions: WalletTransaction[] = [];

  ngOnInit() {
    if (this.token) {
      this.verifySession();
    }
  }

  async verifySession() {
    try {
      const res = await fetch("/api/auth/whoami", {
        headers: { Authorization: `Bearer ${this.token}` }
      });
      if (res.ok) {
        const user = await res.json();
        this.currentUser = user;
        this.fetchWallets();
      } else {
        this.handleSignOut();
      }
    } catch (e) {
      console.error("Failed to verify session:", e);
    }
  }

  async fetchWallets() {
    if (!this.token || !this.userId) return;

    try {
      const res = await fetch(`/api/users/${this.userId}/wallets`, {
        headers: { Authorization: `Bearer ${this.token}` }
      });
      if (res.ok) {
        const list = await res.json();
        this.wallets = list;
        if (list.length > 0 && !this.selectedWallet) {
          this.selectedWallet = list[0];
        }
        this.fetchTransactions();
      }
    } catch (e) {
      console.error("Failed to load wallets:", e);
    }
  }

  async fetchTransactions() {
    if (!this.token || !this.userId || !this.selectedWallet) return;

    try {
      const res = await fetch(`/api/users/${this.userId}/wallets/${this.selectedWallet.id}/transactions`, {
        headers: { Authorization: `Bearer ${this.token}` }
      });
      if (res.ok) {
        this.allTransactions = await res.json();
      }
    } catch (e) {
      console.error("Failed to load transactions for analytics:", e);
    }
  }

  handleLoginSuccess(event: { token: string; userId: string }) {
    localStorage.setItem("harena_token", event.token);
    localStorage.setItem("harena_uid", event.userId);
    this.token = event.token;
    this.userId = event.userId;
    this.verifySession();
  }

  handleSignOut() {
    localStorage.removeItem("harena_token");
    localStorage.removeItem("harena_uid");
    this.token = "";
    this.userId = "";
    this.currentUser = null;
    this.wallets = [];
    this.selectedWallet = null;
    this.allTransactions = [];
    this.analyzingTransaction = null;
    this.activeTab = "dashboard";
  }

  handleWalletSelect(w: Wallet) {
    this.selectedWallet = w;
    this.fetchTransactions();
    this.triggerRefresh();
  }

  handleAnalyzeTransaction(tx: WalletTransaction) {
    this.analyzingTransaction = tx;
    this.activeTab = "ai";
  }

  handleCloseAnalysis() {
    this.analyzingTransaction = null;
  }

  triggerRefresh() {
    this.refreshTrigger++;
    this.fetchWallets();
  }
}
